import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/health': { target: 'http://localhost:8001', changeOrigin: true },
      '/stats': { target: 'http://localhost:8001', changeOrigin: true },
      '/privacy': { target: 'http://localhost:8001', changeOrigin: true },
      '/audit': { target: 'http://localhost:8001', changeOrigin: true },
      '/security': { target: 'http://localhost:8001', changeOrigin: true },
      '/browser': { target: 'http://localhost:8001', changeOrigin: true },
      '/fingerprint': { target: 'http://localhost:8001', changeOrigin: true },
      '/vault': { target: 'http://localhost:8001', changeOrigin: true },
      '/research': { target: 'http://localhost:8001', changeOrigin: true },
      '/search': { target: 'http://localhost:8001', changeOrigin: true },
      '/scrape': { target: 'http://localhost:8001', changeOrigin: true },
      '/act': { target: 'http://localhost:8001', changeOrigin: true },
      '/exec': { target: 'http://localhost:8001', changeOrigin: true },
      '/login': { target: 'http://localhost:8001', changeOrigin: true },
      '/interrupt': { target: 'http://localhost:8001', changeOrigin: true },
      '/workflow': { target: 'http://localhost:8001', changeOrigin: true },
      '/mission': { target: 'http://localhost:8001', changeOrigin: true },
      '/shield': { target: 'http://localhost:8001', changeOrigin: true },
      '/shadow': { target: 'http://localhost:8001', changeOrigin: true },
      '/notifications': { target: 'http://localhost:8001', changeOrigin: true },
      '/vision': { target: 'http://localhost:8001', changeOrigin: true },
      '/forms': { target: 'http://localhost:8001', changeOrigin: true },
      '/local': { target: 'http://localhost:8001', changeOrigin: true },
      '/computer': { target: 'http://localhost:8001', changeOrigin: true },
      '/knowledge': { target: 'http://localhost:8001', changeOrigin: true },
      '/p2p': { target: 'http://localhost:8001', changeOrigin: true },
      '/peer': { target: 'http://localhost:8001', changeOrigin: true },
      '/multimodal': { target: 'http://localhost:8001', changeOrigin: true },
      '/skill': { target: 'http://localhost:8001', changeOrigin: true },
      '/federated': { target: 'http://localhost:8001', changeOrigin: true },
      '/media': { target: 'http://localhost:8001', changeOrigin: true },
      '/models': { target: 'http://localhost:8001', changeOrigin: true },
      '/consensus': { target: 'http://localhost:8001', changeOrigin: true },
      '/harness': { target: 'http://localhost:8001', changeOrigin: true },
      '/llm': { target: 'http://localhost:8001', changeOrigin: true },
      '/v1': { target: 'http://localhost:8001', changeOrigin: true },
      '/ws': { target: 'ws://localhost:8001', ws: true },
    },
  },
})
